### ISSUE TITLE
Adding license

### ISSUE THREAD

**Issue by gwaybio** [xqding/TD-VAE#2]
Hi @xqding - My lab is working on this model for an application to live-cell microscopy images.

We have benefited from your implementation in thinking about how to modify the model for our purposes. Thank you!

Have you thought about adding a permissive open source license (e.g. [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)) to this repository? See [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) for details on adding a license to github.

Adding a license would help us to properly attribute your work, especially as this repository seems to be gaining traction!

Best,
Greg

**Comment by xqding** [comment]
Hi Greg,

I am glad to know that this repository is helpful to you. I have added an MIT license.

**Comment by gwaybio** [comment]
Thank you @xqding
